default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notifier_development

test:
  <<: *default
  database: notifier_test

production:
  <<: *default
  database: notifier_production
  host: <%= ENV['DATABASE_URL'] %>
